mitm:
  host: 127.0.0.1
  port: 8080

webdriver:
  headless: False
  use: chrome
  edge:
    bin: /Users/meizhiwen/Downloads/chromedriver
  chrome:
    bin: /Users/meizhiwen/Downloads/chromedriver
    no_sandbox: True

output:
  use:
    - print
  xml:
    save_path: "./"
    file_pattern: "{room_id}_{ts}.xml"
  debug:
    save_path:
      error: "./error"
      unknown: "./debug"
      known: False

live:
  rooms:
    - "https://live.douyin.com/86948252600"
  users:
    - ""

api:
  userinfo: 'https://live.douyin.com/webcast/user/?aid=6383&target_uid='